name: rag_law_vn

services:
    law-mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: "@12345@"
            MYSQL_DATABASE: law_db
        restart: always
        ports:
            - "2402:3306"
        volumes:
            - law-mysql-data:/var/lib/mysql
        networks:
            - database-network

    law-phpmyadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: law-mysql
            UPLOAD_LIMIT: 300M
        restart: always
        depends_on:
            - law-mysql
        ports:
            - "1312:80"
        networks:
            - database-network

    chromadb:
        image: chromadb/chroma:latest
        restart: always
        ports:
            - "8001:8000"
        volumes:
            - law-chroma-data:/data
        networks:
            - database-network

networks:
    database-network:
        driver: bridge

volumes:
    law-mysql-data:
        name: law-mysql-data

    law-chroma-data:
        name: law-chroma-data